# Generated by Django 4.2.2 on 2023-06-26 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lender",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="lender",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lender",
            name="code",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="lender",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="lender",
            name="trial_commission_rate",
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name="lender",
            name="upfront_commission_rate",
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
